name: APK Yapici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer ile APK Uret
        uses: Akuhov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug
