name: APK Yapici
on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Buildozer ile APK Uret
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug
