name: APK Yapici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Buildozer Kurulumu ve Bagimliliklar
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user --upgrade buildozer cython==0.29.33

      - name: APK Uret
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug
